INSERT INTO business_types (name) VALUES
('Agronegócio'),
('Alimentação'),
('Automotivo'),
('Beleza e Estética'),
('Comércio'),
('Construção Civil'),
('Educação'),
('Entretenimento'),
('Esportes e Fitness'),
('Financeiro'),
('Imobiliário'),
('Indústria'),
('Moda e Vestuário'),
('Saúde'),
('Serviços'),
('Tecnologia'),
('Turismo e Hotelaria'),
('Transporte e Logística');